apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: enoch-server
  name: grafana-deployment-enoch
  labels:
    app: grafana-enoch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-enoch
  template:
    metadata:
      labels:
        app: grafana-enoch
    spec:
      containers:
      - name: grafana-enoch
        image: grafana/grafana:9.4.7
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: grafana-datasource-config.yml
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasource-config
