apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: enoch
  name: blazor-web-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: enoch-kubernetes.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blazor-web-service
            port:
              number: 80