create role azure_pg_admin;
create role shared;
create role "Parker_Swenson_1";
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0 (Debian 16.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ticketsareus; Type: SCHEMA; Schema: -; Owner: azure_pg_admin
--

CREATE SCHEMA ticketsareus;


ALTER SCHEMA ticketsareus OWNER TO azure_pg_admin;
ALTER SCHEMA ticketsareus OWNER TO "Parker_Swenson_1";
ALTER SCHEMA ticketsareus OWNER TO postgres;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: occasion; Type: TABLE; Schema: ticketsareus; Owner: Parker_Swenson_1
--

CREATE TABLE ticketsareus.occasion (
    id integer NOT NULL,
    occasion_name character varying(300),
    time_of_day timestamp with time zone
);


ALTER TABLE ticketsareus.occasion OWNER TO "Parker_Swenson_1";

--
-- Name: occasion_id_seq; Type: SEQUENCE; Schema: ticketsareus; Owner: Parker_Swenson_1
--

ALTER TABLE ticketsareus.occasion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ticketsareus.occasion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: ticketsareus; Owner: Parker_Swenson_1
--

CREATE TABLE ticketsareus.ticket (
    id integer NOT NULL,
    occasion_id integer,
    guid uuid,
    is_used boolean
);


ALTER TABLE ticketsareus.ticket OWNER TO "Parker_Swenson_1";

--
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: ticketsareus; Owner: Parker_Swenson_1
--

ALTER TABLE ticketsareus.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ticketsareus.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: occasion; Type: TABLE DATA; Schema: ticketsareus; Owner: Parker_Swenson_1
--

COPY ticketsareus.occasion (id, occasion_name, time_of_day) FROM stdin;
1	Party Rock	2024-02-08 22:08:33.414+00
2	Jazz Game	2024-02-08 22:21:38.978+00
3	RSL Game	2024-02-08 23:51:31.609+00
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: ticketsareus; Owner: Parker_Swenson_1
--

COPY ticketsareus.ticket (id, occasion_id, guid, is_used) FROM stdin;
133	1	15cf6eb8-9aeb-4390-ba33-737a01d5d274	f
134	1	9de5fce5-488e-42df-b8eb-a43ff6117ba6	f
3	2	3fa85f64-5717-4562-b3fc-2c963f66afa5	f
1	1	3fa85f64-5717-4562-b3fc-2c963f66afa4	t
4	3	3fa85f64-5717-4562-b3fc-2c963f66afa3	f
5	1	3fa85f64-5717-4562-b3fc-2c963f66afa6	f
6	1	3fa85f64-5717-4562-b3fc-2c963f66afa1	f
7	1	3fa85f64-5717-4562-b3fc-2c963f66afa2	f
8	1	3fa85f64-5717-4562-b3fc-2c963f66afb1	f
9	1	3fa85f64-5717-4562-b3fc-2c963f66afb2	f
10	1	3fa85f64-5717-4562-b3fc-2c963f66afb3	f
11	1	3fa85f64-5717-4562-b3fc-2c963f66afb4	f
12	1	3fa85f64-5717-4562-b3fc-2c963f66afb5	f
135	1	bab2a29b-fbbb-48aa-9c7e-0aa4c6f4d6a4	f
136	1	0b37b94f-ee43-4af4-a963-907254bec8b3	f
137	1	cdb41dad-3f16-4851-8231-011823a55861	f
138	1	9ef0e68c-d3db-4d7c-b07c-98bff968218b	f
139	1	951e451d-92d9-4877-ba87-9b6800eee214	f
140	1	be0c1647-e00f-4f8f-bd09-c75de8c9e3c8	f
141	1	e05836b8-5ac8-424b-ae4b-f0de38bd3d40	f
142	1	6e812b5b-45f2-40ed-826c-7edbd3321ffe	f
143	1	d54d74f6-122a-429e-93fe-eda957d01ae8	f
144	1	fb1c9cdc-2e2d-4f7c-b345-44de6e5e28b7	f
145	1	af311a1a-7160-462b-844b-4330848da508	f
146	1	4034fe6d-4189-4bbe-ab20-2a5b8eeb3c1b	f
147	1	c1b2a641-23e4-4b63-b323-b600b60151b7	f
148	1	6662478a-21d1-4421-9a6a-8efeca25af6e	f
\.


--
-- Name: occasion_id_seq; Type: SEQUENCE SET; Schema: ticketsareus; Owner: Parker_Swenson_1
--

SELECT pg_catalog.setval('ticketsareus.occasion_id_seq', 20, true);


--
-- Name: ticket_id_seq; Type: SEQUENCE SET; Schema: ticketsareus; Owner: Parker_Swenson_1
--

SELECT pg_catalog.setval('ticketsareus.ticket_id_seq', 148, true);


--
-- Name: occasion occasion_pkey; Type: CONSTRAINT; Schema: ticketsareus; Owner: Parker_Swenson_1
--

ALTER TABLE ONLY ticketsareus.occasion
    ADD CONSTRAINT occasion_pkey PRIMARY KEY (id);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: ticketsareus; Owner: Parker_Swenson_1
--

ALTER TABLE ONLY ticketsareus.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- Name: ticket ticket_occasion_id_fkey; Type: FK CONSTRAINT; Schema: ticketsareus; Owner: Parker_Swenson_1
--

ALTER TABLE ONLY ticketsareus.ticket
    ADD CONSTRAINT ticket_occasion_id_fkey FOREIGN KEY (occasion_id) REFERENCES ticketsareus.occasion(id);


--
-- PostgreSQL database dump complete
--

