{
 "title": "Logging Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Adding an Event",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Starting Logs for Adding an Event {description}*\""
    }
   ]
  },
  {
   "title": "Getting All Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*All Event.*\""
    }
   ]
  },
  {
   "title": "Getting All Tickets",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*All Ticket.*\""
    }
   ]
  },
  {
   "title": "Getting Single Event By ID",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Single Event.*\""
    }
   ]
  },
  {
   "title": "Getting Single Ticket by ID",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Starting Logs for Getting a Single Ticket by ID.*\""
    }
   ]
  }
 ]
}