{
 "title": "Monitoring Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Observable Gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "Observable_Gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up Down Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "Up_and_Down_Counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "Histogram_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "Basic_Counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Observable Up Down Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "Observable_Up_N_Down", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Observable Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "Observable_Counter", "legendFormat": "__auto" }
   ]
  }
 ]
}