{
 "title": "Visualization Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Attribute Graph",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(Up_and_Down_Counter{job=\"otel-metrics\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram Quantile",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, Histogram_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(Observable_Counter[1d]) + rate(Observable_Up_N_Down[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The Sum of the Observable Gauge ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(Observable_Gauge)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stats Graph",
   "type": "stat",
   "description": "The Average of the Observable Up Down Counter over the last day \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(Observable_Up_N_Down[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}