version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - ../Dump/20240215.09.46.07.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - databaseTunnel
      - otel
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  
  blazorapp:
    build: ..
    ports:
      - 7890:8080
    environment: 
      pec_tickets: user id=postgres; password=postgres; server=db; database=postgres; port=5432;
    depends_on:
      - db 
    networks:
      - databaseTunnel
      - otel
    healthcheck:
      test: curl --fail http://localhost:7890/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  blackbox:
    image: prom/blackbox-exporter:v0.23.0
    container_name: blackbox-enoch
    restart: unless-stopped
    ports:
      - 9101:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      otel:
     
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus-enoch
    hostname: prometheus
    restart: unless-stopped
    ports:
      - 9092:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    depends_on:
      - blackbox
    networks:
      otel:
      
  loki:
    image: grafana/loki:2.8.0
    container_name: loki-enoch
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro      
      - ./loki/loki.yml:/etc/loki/local-config.yaml
    restart: unless-stopped
    ports:
      - 3178:3100
    networks:
      otel:

  grafana-enoch:
    image: grafana/grafana:9.4.7
    container_name: grafana-enoch
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    user: root
    ports:
      - 3078:3000
    depends_on:
      - prometheus
      - loki
    networks:
      otel:
      
  otel-collector:
    container_name: otel-enoch
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped
    ports:
      - 8886:8888   # Prometheus metrics exposed by the collector
      - 8885:8889   # Prometheus exporter metrics
      - 4315:4317   # OTLP gRPC receiver
      - 9205:55679  # zpages
      - 13135:13133 # Health check
    depends_on:
      - zipkin
    networks:
      otel:

  zipkin:
    container_name: enoch-zipkin
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9410:9411
    networks:
      otel:

  # proxy:
  #   image: nginx
  #   container_name: enoch-proxy
  #   ports:
  #     - 3252:80
  #   volumes:
  #     - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - otel
  
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag_enoch
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=enoch-tickets-r-us.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=secrets.DUCKDNSTOKEN
      - STAGING=false #optional
    volumes:
      - swag_data:/config
      - /nginx-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 7922:443
      # - 80:80 #optional
    restart: unless-stopped
     
networks:
  otel:
  databaseTunnel:
    driver: bridge

volumes: 
  grafana-data:
  prometheus:
  swag_data:




