name: enochrunner
on: [push]
    
jobs:
  Deploy:
    runs-on:
      - enoch

    steps:
      - name: "clean/clone" 
        run: |  
          ls -la
          docker compose down -v
          cd ../../
          rm -rf ./ticketsrus-enoch-personal
          git clone https://${{secrets.ENOCH_GITHUB_KEY}}@github.com/enochwhitaker3/ticketsrus-enoch-personal.git
        working-directory: ./EnochStaging

      - name: "build"
        run: |
          ls -la
          docker compose up --build -d
        working-directory: ./../../ticketsrus-enoch-personal/ticketsrus-enoch-personal/EnochStaging

  success:
    name: One with everything
    runs-on: enoch
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.ENOCH_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}

  if_failure:
    name: Only if failure
    runs-on: enoch
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.ENOCH_WEBHOOK }}